### PR TITLE
chore(travis): Adding node versions and develop branch

### PR DESCRIPTION
**Pull request by andresdavid90**
We should be testing in the latest version of Node 4, 5 and 6. Also, the develop branch should be
integrated into the CI.

### CODE REVIEW

**Comment by andresdavid90** [comment]
I think that the build is failing because of this:

```
npm ERR! peerinvalid The package eslint@3.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-jsx-a11y@1.5.5 wants eslint@^2.10.2 || 3.x
npm ERR! peerinvalid Peer eslint-plugin-import@1.10.2 wants eslint@2.x - 3.x
npm ERR! peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint@^2.9.0
```

Any ideas @baldore?

**Comment by andresdavid90** [comment]
The problem seems to be `eslint-config-airbnb`

**Comment by baldore** [comment]
@andresdavid90 We're gonna have to downgrade eslint. I think it's related to this: https://github.com/airbnb/javascript/issues/936

**Comment by andresdavid90** [comment]
@baldore nevermind... the last commit just fixed the CI issue. Please somebody check and merge this. 🙃

**Comment by baldore** [comment]
hehehehe I found the same solution. Testing in local with Node 4.4.7. I'll close it if everything runs ok.

**Pull request merged**
