### PR TITLE
chore(demo): Adding a large demo

### PR DESCRIPTION
**Pull request by andresdavid90**
Now the user can try the module using a large:demo option where a lot of images are going to be
downloaded, just to be sure that it is going to work for that kind of cases. In the future, this
should be covered by our tests but for now I'm going to add this.

### CODE REVIEW

**Comment by baldore** [comment]
Do you still having that problem with big amounts of images where it stopped unexpectedly or it was fixed with the latest changes?

**Comment by andresdavid90** [comment]
@baldore Let me check right now with 15000 to see what happen.

**Comment by andresdavid90** [comment]
I just checked again the issue with a large number of urls, and apparently the problem was a different thing.

From my investigation, pizza-guy is behaving how it is expected and the 'problem' that we saw about passing a large set or urls and the module missing a few was basically happening because of duplicated entries inside that collection (I was getting data from the [tumblr-lks-downldr](https://github.com/andresdavid90/tumblr-lks-downldr/) module but it seems that the Tumblr API is returning duplicated urls).

I need to work in a fix from that side but I can say for now, that pizza-guy is working like a charm. I'm going to create a PR where we can tell via logs when the data set that's being passed has duplicated entries.

**Comment by baldore** [comment]
Awesome!

**Comment by entrptaher** [comment]
I have a small question. 
Is there a problem using a json file instead? 
One can easily export a list to a JSON file instead of a JS file. 
Tho both works same way in this example, but wouldn't it be better to use a JSON list instead?
From there, we can go on with a txt list too.

**Comment by andrscrrn** [comment]
@entrptaher Well, we don't have any problem about using a JSON file, but for the demo purposes it doesn't matter. Why do you say it would be better to use a JSON file?

**Comment by entrptaher** [comment]
The only thing came into my mind was, 
you can use JSON with pretty much every language. And it's pure data that can be updated with external tools. 
JS exports are better in many cases, but we are dealing with downloads here.

**Pull request merged**
